app = "gurddy-mcp"
primary_region = "lax"
[[services]]
  internal_port = 8080
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 250
    soft_limit = 200

  [[services.ports]]
    port = "5000"

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000
